version: '3.5'

services:
  tdd:
    image: ${DOCKERHUB_USER}/tdd:${TDD_TAG}
    environment:
      TELEGRAM_DAEMON_API_ID: "${API_ID}"
      TELEGRAM_DAEMON_API_HASH: "${API_HASH}"
      TELEGRAM_DAEMON_CHANNEL: "${TELEGRAM_DAEMON_CHANNEL}"
      TELEGRAM_DAEMON_DEST: "/downloads"
      TELEGRAM_DAEMON_TEMP: "/tmp"
      TELEGRAM_DAEMON_SESSION_PATH: "/session"
    volumes:
       - ${HOST_TELEGRAM_DAEMON_SESSION_PATH}:/session
       - ${HOST_TELEGRAM_DAEMON_DEST}:/downloads
       - ${HOST_TELEGRAM_DAEMON_TEMP}:/tmp
    restart: unless-stopped