#!/bin/bash

echo "TELEGRAM_DAEMON_API_ID={$TELEGRAM_DAEMON_API_ID}"
echo "TELEGRAM_DAEMON_API_HASH={$TELEGRAM_DAEMON_API_HASH}"
echo "TELEGRAM_DAEMON_CHANNEL={$TELEGRAM_DAEMON_CHANNEL}"
echo "TELEGRAM_DAEMON_DEST={$TELEGRAM_DAEMON_DEST}"
echo "TELEGRAM_DAEMON_TEMP={$TELEGRAM_DAEMON_TEMP}"


python3 ./telegram-download-daemon.py